---
- block:

  - name: install dependencies
    package:
      name: "{{ item }}"
      state: installed
    with_items: "{{ hubot_dep_pkgs }}"
    tags:
      - hubot_pkg_install_deps

  - name: install generator-hubot
    npm:
      name: "{{ item }}"
      global: yes
      state: present
    with_items: "{{ hubot_dep_npm_pkgs }}"
    tags:
      - hubot_npm_install_generator_hubot

  - name: install npm packages
    npm:
      name: "{{ item }}"
      global: yes
      state: present
    with_items: "{{ hubot_hubot_pkgs }}"
    tags:
      - hubot_npm_install_deps

  - name: Install Hubot
    command: yo hubot --name="{{ hubot_name }}" --description="{{ hubot_description }}" --adapter="{{ hubot_adapter }}" --owner="{{ hubot_admin }}"
    args:
      chdir: "{{ hubot_home }}"
      creates: "{{ hubot_name }}-{{ hubot_version }}.log"

  - name: Create group
    group:
      name: "{{ hubot_group }}"
      state: present

  - name: Create user
    user:
      name: "{{ hubot_user }}"
      state: present
      shell: '/bin/bash'
    tags:
      - hubot_create_users_groups

  - name: Set file permissions
    file:
      path: "{{ hubot_home }}"
      recurse: yes
      owner: "{{ hubot_user }}"
      group: "{{ hubot_group }}"
      state: directory     

  - name: install systemd service file
    template:
      src: "templates/etc/systemd/system/hubot-slack.service.j2"
      dest: "/etc/systemd/system/hubot.service"
      owner: root
      group: root
      mode: "0644"
    notify: restart hubot
    when: '"{{ hubot_adapter }}" == "slack"'
    tags:
      - hubot_install_systemd_service_file

  - name: install environment file
    template:
      src: "templates/etc/hubot/hubot-env-variables.j2"
      dest: "{{ hubot_home }}hubot-env-variables"
      owner: root
      group: root
      mode: "0644"
    notify: restart hubot
    when: not ("{{ hubot_adapter }}" == "slack")
    tags:
      - hubot_install_environment_file

  - name: install systemd service file
    template:
      src: "templates/etc/systemd/system/hubot.service.j2"
      dest: "/etc/systemd/system/hubot.service"
      owner: root
      group: root
      mode: "0644"
    notify: restart hubot
    when: not ("{{ hubot_adapter }}" == "slack")
    tags:
      - hubot_install_systemd_service_file

  - name: start/enable hubot service
    systemd:
      name: hubot
      state: started
      enabled: yes
    tags:
      - hubot_start_service
      - hubot_enable_service

  tags:
    - hubot
